version: '3'
tasks:
  clean:
    run: once
    desc: Deletes build/ directory
    cmds:
      - rm -fr build/
  compileAssets:
    run: once
    desc: Compiles assets into go code
    cmds:
      - go-bindata -o generated/assets/assets.go -pkg assets -prefix assets/ assets/
  build:
    run: once
    deps: [compileAssets]
    desc: Compiles game
    cmds:
      - go build -o ./build/client{{exeExt}} main.go
  run:
    run: once
    deps: [build]
    desc: Runs game
    cmds:
      - ./build/client{{exeExt}}
